# Generated by Django 3.0.6 on 2020-06-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_posted',
            new_name='submission_date',
        ),
    ]
